version: '3.8'
services:
  db:
    container_name: postgres-reservations
    image: reservations-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: