services:
  db:
    image: postgres:16.4-alpine3.20
    restart: on-failure
    shm_size: 128mb
    container_name: reservations-postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - reservations_postgres_data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      - reservations-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reservations-backend
    ports:
      - "8082:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    networks:
      - reservations-network

networks:
  reservations-network:
    driver: bridge

volumes:
  reservations_postgres_data: